### ISSUE TITLE
Need to integrate a DB for storing data

### ISSUE THREAD

**Issue by ankan-withadream** [ankan-withadream/kiGo#13]
As discussed with @ama3it , we will be integrating a Postgress DB.

**Comment by ankan-withadream** [comment]
Somehow we have to find a free Postgress DB server for now to integrate.

**Comment by ama3it** [comment]
Will host a Amazone RDS instance with PostgreSQL engine.
https://aws.amazon.com/rds

**Comment by ankan-withadream** [comment]
Created a postgresql cluster in EDB Big Animal host. Will live for 30 days as it is free tier :(  
I will main you the db details @ama3it 

Also had a proposal to use mysql as it has some really free hostings. [db4free](https://www.db4free.net/)
